package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/msoft-g1/todo-list-backend/internal/errs"
	"github.com/msoft-g1/todo-list-backend/internal/graph/generated"
)

// Code is the resolver for the code field.
func (r *errorResolver) Code(ctx context.Context, obj *errs.Error) (string, error) {
	return string(obj.Code), nil
}

// Error returns generated.ErrorResolver implementation.
func (r *Resolver) Error() generated.ErrorResolver { return &errorResolver{r} }

type errorResolver struct{ *Resolver }
