// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package modelgen

import (
	"github.com/msoft-g1/todo-list-backend/internal/domain/task"
	"github.com/msoft-g1/todo-list-backend/internal/domain/user"
)

// Mutation operations
type Mutation struct {
}

// Query operations
type Query struct {
}

type TaskCreatePayload struct {
	Task *task.Task `json:"task,omitempty"`
}

type TaskDeletePayload struct {
	Ok bool `json:"ok"`
}

type TaskUpdatePayload struct {
	Task *task.Task `json:"task,omitempty"`
}

type UserAccessTokenCreatePayload struct {
	UserAccessToken *string `json:"userAccessToken,omitempty"`
}

type UserAccessTokenRenewPayload struct {
	UserAccessToken *string `json:"userAccessToken,omitempty"`
}

type UserCreatePayload struct {
	User *user.User `json:"user,omitempty"`
}
